version: '3.8'

services:
  python:
    build: .
#    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data/:/usr/src/app/data/
      - ./logs/:/usr/src/app/logs/
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dyson
      - POSTGRES_PASSWORD=dyson
      - POSTGRES_DB=superhero
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      

volumes:
  postgres_data: